Update lateststart.yml

diff --git a/.github/workflows/lateststart.yml b/.github/workflows/lateststart.yml
--- a/.github/workflows/lateststart.yml
+++ b/.github/workflows/lateststart.yml
@@ -49,13 +49,15 @@ jobs:
           else
             echo "JDK 17 is already installed."
           fi
-          cd /home/ubuntu/212024
-          sudo su
+          cd /home/${{ secrets.USERNAME }}/212024
           git pull https://github.com/Dhananjaybobde007/212024.git
-          latest_jars=$(find . -name "*.jar" | sort | tail -n 1)
-          echo "Extracted filename: $latest_jars"
-          # Navigate to the application directory and run the new JAR file
-          latest_jars=$(basename "$latest_jars")
-          sudo java -jar "$latest_jars" &
+          latest_jar=$(find . -name "*.jar" | sort | tail -n 1)
+          if [ -z "$latest_jar" ]; then
+            echo "Error: No JAR file found in the repository."
+            exit 1
+          fi
+          latest_jar=$(basename "$latest_jar")
+          echo "Starting JAR file: $latest_jar"
+          sudo java -jar "$latest_jar" &
           sleep 10
           echo "New JAR file is running."
